### ISSUE TITLE
Code compilation error

### ISSUE THREAD

**Issue by KamelMoohamed** [KshitijKarnawat/Structure-from-Motion#3]
When I am trying to run the calibrate.py or the generate_point_cloud.py, I got a compilation in the both files

**Comment by KshitijKarnawat** [comment]
Hi Kamel,

Can you please post the exact error so that we can figure out what is wrong.

Also for calibration.py you can refer [this tutorial by OpenCV](https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html) till we can work things out.

Thanks
Kshitij Karnawat

**Comment by KamelMoohamed** [comment]
First, thanks for fast replying; I am very grateful for that.

 - In the calibrate.py file, I got an error that the `gray` variable can't be found, I didn't want to change anything; however, When I updated it to be inside the loop, it worked correctly.

 - For the generate_point_cloud.py --> It can't find the two images in the same directory, so I didn't understand what should I change. Should I get two samples from the data or change the path? 

If you can provide me with clear steps to run the project without the hardware, I will be very thankful for that. I just want to run the project with your data and see the output live.

Thanks
Kamel Mohamed

**Comment by KshitijKarnawat** [comment]
> In the calibrate.py file, I got an error that the gray variable can't be found, I didn't want to change anything; however, When I updated it to be inside the loop, it worked correctly.

Glad you were able to fix this.

> For the generate_point_cloud.py --> It can't find the two images in the same directory, so I didn't understand what should I change. Should I get two samples from the data or change the path?

Yes for this you will have to change the path to load the images. generate_point_cloud.py will not give you the best results though. For best results I would recommend using depth_nn.py and pc_stitching.py.

If you would like to see the results you can view them here https://arxiv.org/abs/2306.06360

> If you can provide me with clear steps to run the project without the hardware, I will be very thankful for that. I just want to run the project with your data and see the output live.

I'll update the readme file and the dataset with detailed steps in a few days.

**Comment by KamelMoohamed** [comment]
OK I will try it, thanks a lot for your replying
